### Without Authorization header
# Send a GET request without the 'Authorization' header
GET http://localhost:5000
?? status == 403
?? body == Authorization header not set

---

### Invalid Iss
# Test Request With a JWT Token (Invalid Issuer)
GET http://localhost:5000
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwiaXNzIjoiTWljcm9zb2Z0IiwiaWF0IjoxNTE2MjM5MDIyfQ.plgc851zioEJVkmO3xX9DT86eP-A5x5-aauFAadePUIfwnhdglsxqsY6e7bkKHw15ssAyoXM0atDJSdYLfZaONW1JtnFW388BxhVNHebXphaK_-HvkjtlJpkr8ZFvlTvaDvGiMqqt8wLoWSW-1fHYzWOFmTyWTDKbgPYurg9caHdLpIfqMpC3x9mNGbKQIXVUGA2lonePMznHmjcvjETqwlNMVxIfx0AqNyl_ELTCpFREOLnXB58isLmramsjwD9zLr4Mk4yy5Z4fGWnU3UKJ2TTNdX1hwhZMsGF3Wq_DVyjGCiE-b12n9yWfUliuXrtOvUu1TsiG-68bBkkrwHl0g
?? status == 403
?? body == This token with issuer 'Microsoft' doesn't belong to this domain

---

### Valid Iss
# Test Request With a JWT Token (Valid Issuer)
GET http://localhost:5000
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwiaXNzIjoiUmF5dmFyeiJ9.Dz3haMZfXwHOT4_k4nOecpKqz6aXZCIBCMBXX6q2WiZfrVe0M-OjNWiZaXv7ZZ6UtDpC6phgkYBfXgUu_HUX0x1ND694VNvHt2dF3CFsMLJH6HpVLSdXuapzFKFWYF7HI8sTW0nPSAi7QkEezSxuP7QtUR-JjEVO2iX0RaVixrbBnK8hOWj_Gi-1tBiTd3pt_-6Zc41OlAE0CAW8jCxnU60mAjm-QxdoJfiBcb54kM4h-Ih5EWV8kH_AU1l2wRTBJoN7vOxUqdGkJ5HJUMsTGhwjVrobEnyUYh9htwIAfg6gdDsnB8nopMJO1hmdle1LraApNoxz1PsKIQWVdhxygg
?? status == 200

---

### Iat (Refresh Token)
# Test Request With a JWT Token ('iat')
GET http://localhost:5000
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwiaXNzIjoiUmF5dmFyeiIsImlhdCI6MTY5ODU4MDgyMX0.i3QfSfXvkAdxrS_u7X5R_PNbxddYdV2FQ9tlceyamlB4kIGkgEuF8PRYoRqXznKQQ3Zlc1s7WkWOzh5OXuF5RHh7O_X0mZwo2_dSI_JK-0M1T6-tupIvwwIZAYRyYKZ60A8iHPihTySz-VdE7II6og-i8NeszAaqR8X_4cQ-cdK7y6upKxjMVD-xVRQjo61Qke0j0gA2ZfJr7unm2h3ynioj35mh7EPFkrX3cUmbd7AOYwIVPDMd4L75vbZ6k1TMLwH7OrfCuYZQTcBpv9BzDeuKBY_niQpMELs8NQa2wF71tdA7yixFc2zv2Jh2T1SRtCbR2nSiDZKhUZisU-SHUg
?? status == 403
?? body == Refresh Token

---

### Expired Token
# Test Request With a JWT Token ('exp')
GET http://localhost:5000
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwiZXhwIjoxNjk2MTE4NDAxfQ.TPpQMjTbAnh__IAwJRZmsK5XX53KJBxsojHxFCNLPvEQbCldcT49TSQATpG7ZhtQJ61-AZLic2oOGyTCg1pLPEstxZukSoKs3osYp0x8cLNCwx0uJ8ILY8KTTvCDEjQZbEaeepoQe-beK26LT1TKCc2jwzhPqMo45OqifPPgnsdYgRm0efw4JFBgPHgb38Q6n5Cyx09S-Vv4hbTeGu1gcHc5vHUaEqVV_8LG5MkPhd1_WN88kZgM2ADbYRl_pQljTUwV4ev8mKANLvMxLQZ3G_6nNjhieOJfhl0EEHo1rinXHt3qH3z95pST_k9zdJKFmu8mT3_6PUxm0Pbs7Nc3tQ
?? status == 403
?? body == Token Expired

### UserID
# Test Request With a JWT Token ('UserID')
GET http://localhost:5000
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwiaXNzIjoiUmF5dmFyeiIsIlVzZXJJRCI6IjEwMDEifQ.buwnGmi-KrCcohWS1_pLVKsgi9v6fvxe-woYmhKOAD-sMXzNLG8H8k-lXWF2YAn7emydxiP8fGhC7dUK8O8Pg6UoQR5u4XNbx210Y-EIK_DAu_T1Vp6yWSTfo_W_i6pxa2nIIRhSge9S1zjIL3luhtZlI0MBSmBYG3NCnqvC_Dy2KxFjAKzbADK4QbbntK841fpihgD8H-WWGcuuw1I_yrV0_M-AgN6ol_te5D8qg9TJZZ1EH9RbBA-abUSOkV39AzEkBH8hQ-3dNN-fkqB6YMFgXwk6ZAAfOaB9iLWqyWM6i0kl1eCcmks278EOO8UFN4ZI3zn-UeZ8sF1h-d10lw
?? status == 200

### Unauthorized User
# Test Request With an Unauthorized UserID
GET http://localhost:5000
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwiaXNzIjoiUmF5dmFyeiIsIlVzZXJJRCI6IjEwMDIifQ.Hi2nHfUdxE8sOF_NSowLx97ZOP27Te0tMa3qcmc3DEAU4RATylmYz91O1dz5Yq10uxu6tDHjPsKHFIK5Hhrmfp8m485mCjiHY1_8FOV6pGH4vMbiqL45dbGaZGS7T8NixxYpNryMpXXPFy_nehCngbERv8cYAhrilF0Xvrg2DvEbeUiqRwTMPwFm4wglM7VAdFSYPyPcGt5pFixYsD3NUHE6LIcFj-N62Y3F_cISMFHMHEQSemDO-zQsEfNWk09GWNZm7P0DVqQ4VekxV7giSXf8YRZBdMDXmNrsN9yyppVcCKr575uCEy-cthGSyAHWejjoC-_QlJiDNLo3amFU6g
?? status == 403
?? body == Unauthorized User

### GetCurrentUser
GET http://localhost:5000/GetCurrentUser
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwiaXNzIjoiUmF5dmFyeiIsIlVzZXJJRCI6IjEwMDEifQ.buwnGmi-KrCcohWS1_pLVKsgi9v6fvxe-woYmhKOAD-sMXzNLG8H8k-lXWF2YAn7emydxiP8fGhC7dUK8O8Pg6UoQR5u4XNbx210Y-EIK_DAu_T1Vp6yWSTfo_W_i6pxa2nIIRhSge9S1zjIL3luhtZlI0MBSmBYG3NCnqvC_Dy2KxFjAKzbADK4QbbntK841fpihgD8H-WWGcuuw1I_yrV0_M-AgN6ol_te5D8qg9TJZZ1EH9RbBA-abUSOkV39AzEkBH8hQ-3dNN-fkqB6YMFgXwk6ZAAfOaB9iLWqyWM6i0kl1eCcmks278EOO8UFN4ZI3zn-UeZ8sF1h-d10lw
?? status == 200
?? body == AlirezaAlavi

### GetRoles
GET http://localhost:5000/GetRoles
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwiaXNzIjoiUmF5dmFyeiIsIlVzZXJJRCI6IjEwMDEifQ.buwnGmi-KrCcohWS1_pLVKsgi9v6fvxe-woYmhKOAD-sMXzNLG8H8k-lXWF2YAn7emydxiP8fGhC7dUK8O8Pg6UoQR5u4XNbx210Y-EIK_DAu_T1Vp6yWSTfo_W_i6pxa2nIIRhSge9S1zjIL3luhtZlI0MBSmBYG3NCnqvC_Dy2KxFjAKzbADK4QbbntK841fpihgD8H-WWGcuuw1I_yrV0_M-AgN6ol_te5D8qg9TJZZ1EH9RbBA-abUSOkV39AzEkBH8hQ-3dNN-fkqB6YMFgXwk6ZAAfOaB9iLWqyWM6i0kl1eCcmks278EOO8UFN4ZI3zn-UeZ8sF1h-d10lw
response:
    status: 200
    body: '["Admin", "Customer"]'

### Invalid Key
GET http://localhost:5000
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwiaXNzIjoiTWljcm9zb2Z0IiwiaWF0IjoxNTE2MjM5MDIyfQ.cHYgfjTvW-ng8AG2Li5wBcBiwKjrkZI8PCKh32W1qAchCmqBlebV0I5IYgu8ZHLt4pI5rCeZpPU4pCI8jRviXKZexUEg8B4AGHys03nlBx2g_QHJv3XUp-DdR9Zfweag-8YCIr7Mg60Eg7bYNYB44G_F1zXP3D797pQF38O84PT7bYqKopJqcrz_uSfz_BfQd_h5txLxF-Vv0EfatAzG9nVkt5c25BC7mohIp8f2ffS2CPk4D87Um-SN9xJAI4woGyyZPuUvQQfPVWuCZI0I4-lWx5EX8IorgInmDxrU9kXmDZ1GxyXv9-2gwNTGzAv2lxPIq7wIhjZf_KWNHM9P7w
?? status == 403

### Without Key
GET http://localhost:5000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c